name: Generate Artifacts

on:
  push:
    branches:
      - main
    paths:
      - '**.proto'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Buf
        uses: bufbuild/buf-setup-action@v1

      - name: Generate protobuf code
        run: buf generate

      - name: Push TypeScript to PNPM
        if: always()
        run: |
          cd generated/ts
          pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Java
        if: always()
        run: |
          cd generated/java
          mvn deploy
        env:
          MAVEN_USERNAME: github
          MAVEN_TOKEN: ${{ secrets.GITHUB_TOKEN }}
